export const entityList = [
  { name: 'Shop' },
  { name: 'City' },
  { name: 'Order' },
  { name: 'Customer' },
  { name: 'Contact' },
  { name: 'Product' },
  { name: 'Manufacture' },
  { name: 'Remind' },
  { name: 'Rejection' },
  { name: 'Payment' },
  { name: 'PaymentService' },
  { name: 'Delivery' },
  { name: 'DeliveryService' },
  { name: 'User' },
  { name: 'Role' },
  { name: 'Permission' },
  { name: 'Image' },
];
